### ISSUE TITLE
Unhandled error printout with cli client

### ISSUE THREAD

**Issue by fubuloubu** [fief-dev/fief-python#18]
## Describe the bug

I followed the docs for the cli version of the client (which works!), however it seems like an unhandled exception towards the end of that process keeps printing to the console

## To Reproduce

Followed steps from here: https://docs.fief.dev/integrate/python/cli/

```py
In [3]: client.authorize()
Out [3]: ...  # access_token stuff
Error in callback <function Halo.__init__.<locals>.clean_up at 0x744c898153a0> (for post_run_cell), with arguments args (<ExecutionResult object at 744c898249d0, ...
TypeError: Halo.__init__.<locals>.clean_up() takes 0 positional arguments but 1 was given
```

## Expected behavior

Doesn't appear to affect operation, but is annoying to see this error no matter what is happening lol

## Configuration

* Python version:3.11.9
* Fief client version: 0.18.6

* Fief Cloud or self-hosted: self-hosted (Railway)
* If self-hosted, Fief version: 0.28.6

## Additional context

Very sweet having a CLI client! (need it for our use case)

**Comment by fubuloubu** [comment]
related: https://github.com/manrajgrover/halo/pull/180

`halo` seems unmaintained

**Comment by fubuloubu** [comment]
This seems much more active: https://pypi.org/project/yaspin/

**Comment by frankie567** [comment]
Good catch, thank you! Would be happy to review a PR replacing halo by yaspin :)

**Comment by fubuloubu** [comment]
> Good catch, thank you! Would be happy to review a PR replacing halo by yaspin :)

Yeah will do, this seems like an easy migration lol
